name: Bitcoin Bot 24/7

on:
  schedule:
    # Roda a cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          # Mantemos o 3.10 que é o mais compatível
          python-version: '3.10' 

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          
          # Bibliotecas padrão
          pip install ccxt pandas firebase-admin requests
          
          # CORREÇÃO AQUI: Instalando via ZIP para não pedir senha/login
          pip install https://github.com/twopirllc/pandas-ta/archive/development.zip

      - name: Rodar o Robô
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
