name: Bitcoin Bot 24/7

on:
  schedule:
    # Roda a cada 5 minutos (*/5)
    # Nota: O GitHub pode atrasar alguns minutos se estiver sobrecarregado, isso é normal.
    - cron: '*/5 * * * *'
  
  # Permite rodar manualmente clicando no botão se você quiser testar
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas pandas_ta firebase-admin requests

      - name: Rodar o Robô
        env:
          # AQUI ENTRAM SUAS CHAVES (Configure em Settings > Secrets and variables > Actions)
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
