name: Bitcoin Bot 24/7

on:
  schedule:
    # Roda a cada 5 minutos
    - cron: '*/5 * * * *'
  
  # Permite rodar manualmente para testar
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # --- CORREÇÃO AQUI: Mudamos de 3.9 para 3.12 ---
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          # Instalamos o pandas_ta direto do git para garantir compatibilidade, junto com as outras libs
          pip install ccxt pandas firebase-admin requests
          pip install git+https://github.com/twopirllc/pandas-ta.git@development

      - name: Rodar o Robô
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
